/**
 * test/repatch_captions.test.js
 *
 * PR-AF: lockdown tests for applyAssReplacements. The runRepatchCaptions
 * + repatchCaptionsOnDisk wrappers are not unit-tested here — they shell
 * out to ffmpeg, which we don't run in CI.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { applyAssReplacements } from '../lib/repatch_captions.js';

// A representative slice of what generateAss produces in the orchestrator —
// headers + Style: + Format: + a handful of Dialogue: lines.
const SAMPLE_ASS = `[Script Info]
Title: Generated by clean_mode_pipeline.js
ScriptType: v4.00+
PlayResX: 1080
PlayResY: 1920

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Montserrat,50,&H00FFFFFF,&H000000FF,&H001A1A1A,&H00000000,-1,0,0,0,100,100,1,0,1,4,2,2,40,40,200,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.20,0:00:03.45,Default,,0,0,0,,A SPECIALIST CAN HELP
Dialogue: 0,0:00:04.10,0:00:05.92,Default,,0,0,0,,WE OFFER SPECIALIST CARE
Dialogue: 0,0:00:07.30,0:00:09.10,Default,,0,0,0,,I WANDERED IF YOU MIGHT KNOW
Dialogue: 0,0:00:10.50,0:00:12.00,Default,,0,0,0,,SOMETHING UNRELATED HERE
`;

// ── applyAssReplacements — happy path ──────────────────────────────────

test('applyAssReplacements: single literal replacement modifies dialogue text only', () => {
  const { text, results } = applyAssReplacements(SAMPLE_ASS, [
    { from: 'SPECIALIST', to: 'SPECIAL NEEDS' },
  ]);
  // Two SPECIALIST occurrences in two Dialogue lines.
  assert.equal(results.length, 1);
  assert.equal(results[0].count, 2);
  assert.equal(results[0].from, 'SPECIALIST');
  assert.equal(results[0].to, 'SPECIAL NEEDS');
  // Verify the swap actually landed.
  assert.match(text, /A SPECIAL NEEDS CAN HELP/);
  assert.match(text, /WE OFFER SPECIAL NEEDS CARE/);
  // And the unrelated line + headers are untouched.
  assert.match(text, /SOMETHING UNRELATED HERE/);
  assert.match(text, /PlayResX: 1080/);
});

test('applyAssReplacements: multiple replacements compose in order', () => {
  const { text, results } = applyAssReplacements(SAMPLE_ASS, [
    { from: 'SPECIALIST', to: 'SPECIAL NEEDS' },
    { from: 'WANDERED', to: 'WONDERED' },
  ]);
  assert.equal(results[0].count, 2);
  assert.equal(results[1].count, 1);
  assert.match(text, /SPECIAL NEEDS CAN HELP/);
  assert.match(text, /I WONDERED IF YOU MIGHT KNOW/);
});

test('applyAssReplacements: zero matches returns count=0 and unchanged text on dialogue', () => {
  const { text, results } = applyAssReplacements(SAMPLE_ASS, [
    { from: 'NEVER_APPEARS', to: 'REPLACED' },
  ]);
  assert.equal(results[0].count, 0);
  // Dialogue lines should be exactly equal to original.
  const origDialogue = SAMPLE_ASS.split('\n').filter((l) => l.startsWith('Dialogue:')).join('\n');
  const newDialogue = text.split('\n').filter((l) => l.startsWith('Dialogue:')).join('\n');
  assert.equal(newDialogue, origDialogue);
});

// ── boundaries: only dialogue lines are touched ─────────────────────────

test('applyAssReplacements: never touches Style: lines (font name protected)', () => {
  // Even if the operator stupidly tries to replace "Montserrat", style is
  // off-limits — we only mutate Dialogue:.
  const { text, results } = applyAssReplacements(SAMPLE_ASS, [
    { from: 'Montserrat', to: 'ComicSans' },
  ]);
  assert.equal(results[0].count, 0);
  assert.match(text, /Style: Default,Montserrat,50/);
});

test('applyAssReplacements: never touches header / format lines', () => {
  // Replacement that would have matched "Format:" in the header — also
  // ignored. Only Dialogue: lines are in scope.
  const withFormatStr = SAMPLE_ASS.replace('SOMETHING UNRELATED HERE', 'FORMAT HERE');
  const { text, results } = applyAssReplacements(withFormatStr, [
    { from: 'FORMAT', to: 'PATCHED' },
  ]);
  // Only the dialogue line should change, not the [V4+ Styles] Format: line.
  assert.equal(results[0].count, 1);
  assert.match(text, /Format: Name, Fontname/); // header preserved
  assert.match(text, /PATCHED HERE/);            // dialogue swapped
});

// ── regex mode ─────────────────────────────────────────────────────────

test('applyAssReplacements: regex mode with capture groups', () => {
  const ass = `[Events]
Dialogue: 0,0:00:01.20,0:00:03.45,Default,,0,0,0,,IT'S 50% OFF TODAY
Dialogue: 0,0:00:04.10,0:00:05.92,Default,,0,0,0,,SAVE 75% ON CARE
`;
  const { text, results } = applyAssReplacements(ass, [
    { from: '(\\d+)%', to: '$1 PERCENT', mode: 'regex' },
  ]);
  assert.equal(results[0].count, 2);
  assert.match(text, /IT'S 50 PERCENT OFF TODAY/);
  assert.match(text, /SAVE 75 PERCENT ON CARE/);
});

test('applyAssReplacements: regex mode with case-insensitive flag', () => {
  const ass = `[Events]
Dialogue: 0,0:00:01.20,0:00:03.45,Default,,0,0,0,,Help me please
Dialogue: 0,0:00:04.10,0:00:05.92,Default,,0,0,0,,HELP WANTED
`;
  const { text, results } = applyAssReplacements(ass, [
    { from: 'help', to: 'assist', mode: 'regex', caseInsensitive: true },
  ]);
  assert.equal(results[0].count, 2);
  assert.match(text, /assist me please/);
  assert.match(text, /assist WANTED/);
});

test('applyAssReplacements: invalid regex pattern throws with replacement index', () => {
  assert.throws(
    () => applyAssReplacements(SAMPLE_ASS, [
      { from: 'fine', to: 'good' },
      { from: '(unclosed', to: 'X', mode: 'regex' },
    ]),
    /replacement 1.*invalid pattern.*\(unclosed/,
  );
});

// ── literal-mode escapes regex metachars ────────────────────────────────

test('applyAssReplacements: literal mode treats . as literal (not regex wildcard)', () => {
  const ass = `[Events]
Dialogue: 0,0:00:01.20,0:00:03.45,Default,,0,0,0,,WWW.SITE.COM IS HERE
Dialogue: 0,0:00:04.10,0:00:05.92,Default,,0,0,0,,WWWXSITEXCOM SHOULD NOT MATCH
`;
  const { text, results } = applyAssReplacements(ass, [
    { from: 'WWW.SITE.COM', to: 'NEW_URL' },
  ]);
  // Literal mode: only the actual "WWW.SITE.COM" matches, not the regex-
  // wildcard "WWWXSITEXCOM" interpretation.
  assert.equal(results[0].count, 1);
  assert.match(text, /NEW_URL IS HERE/);
  assert.match(text, /WWWXSITEXCOM SHOULD NOT MATCH/); // unchanged
});

// ── input validation ─────────────────────────────────────────────────

test('applyAssReplacements: non-string assText throws', () => {
  assert.throws(() => applyAssReplacements(null, [{ from: 'a', to: 'b' }]), /must be a string/);
  assert.throws(() => applyAssReplacements(123, [{ from: 'a', to: 'b' }]), /must be a string/);
});

test('applyAssReplacements: empty / null replacements returns text unchanged', () => {
  const { text: a, results: ra } = applyAssReplacements(SAMPLE_ASS, []);
  assert.equal(a, SAMPLE_ASS);
  assert.equal(ra.length, 0);

  const { text: b } = applyAssReplacements(SAMPLE_ASS, null);
  assert.equal(b, SAMPLE_ASS);
});

test('applyAssReplacements: malformed Dialogue: line is left untouched', () => {
  // Dialogue with fewer than 10 commas → can't reliably find text field.
  // Better to skip than to mangle.
  const malformed = `[Events]
Dialogue: malformed_line_no_commas
Dialogue: 0,0:00:01.20,0:00:03.45,Default,,0,0,0,,WELL FORMED
`;
  const { text, results } = applyAssReplacements(malformed, [
    { from: 'WELL', to: 'BADLY' },
  ]);
  assert.equal(results[0].count, 1);
  assert.match(text, /Dialogue: malformed_line_no_commas/); // unchanged
  assert.match(text, /BADLY FORMED/);                       // valid line patched
});

// ── PR-AF: Chelsea's specific QC examples (regression) ─────────────────

test("PR-AF regression: Chelsea's Tue 19 — 'SPECIALIST' → 'SPECIAL NEEDS' (2 matches)", () => {
  // Mirrors the actual Tue 19 caption at 0:32 and 1:07.
  const { results } = applyAssReplacements(SAMPLE_ASS, [
    { from: 'SPECIALIST', to: 'SPECIAL NEEDS' },
  ]);
  assert.equal(results[0].count, 2);
});

test("PR-AF regression: Chelsea's Thurs 21 — 'WANDERED' → 'WONDERED' (1 match)", () => {
  const { results } = applyAssReplacements(SAMPLE_ASS, [
    { from: 'WANDERED', to: 'WONDERED' },
  ]);
  assert.equal(results[0].count, 1);
});
