import { Router } from 'express';
import { writeFileSync, existsSync, readFileSync } from 'fs';
import { spawn } from 'child_process';
import { chromium } from 'playwright';

export const youtubeAuthRouter = Router();

// In-memory cookies cache — survives requests within the same Railway deployment.
// Updated by /refresh-youtube-cookies and read by getYtDlpAuthArg() in youtube.js.
let _cachedCookiesStr = null;

/**
 * Get the in-memory cached cookies string, if any.
 * Called by youtube.js before falling back to the YOUTUBE_COOKIES env var.
 */
export function getCachedCookies() {
  return _cachedCookiesStr;
}

/**
 * Format Playwright cookies array as Netscape cookies.txt (yt-dlp compatible).
 */
function toNetscapeCookies(cookies) {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by media-worker /refresh-youtube-cookies'];
  for (const c of cookies) {
    const domain = c.domain.startsWith('.') ? c.domain : `.${c.domain}`;
    const secure = c.secure ? 'TRUE' : 'FALSE';
    const expires = c.expires > 0
      ? Math.floor(c.expires)
      : Math.floor(Date.now() / 1000 + 2 * 365 * 24 * 3600);
    const path = c.path || '/';
    lines.push(`${domain}\tTRUE\t${path}\t${secure}\t${expires}\t${c.name}\t${c.value}`);
  }
  return lines.join('\n');
}

/**
 * Update YOUTUBE_COOKIES env var on Railway via GraphQL API.
 * Uses built-in RAILWAY_PROJECT_ID, RAILWAY_SERVICE_ID, RAILWAY_ENVIRONMENT_ID env vars
 * (automatically injected by Railway into every deployed service).
 * Requires RAILWAY_TOKEN to be set manually in Railway env vars.
 */
async function updateRailwayEnvVar(cookiesStr) {
  const token = process.env.RAILWAY_TOKEN;
  const projectId = process.env.RAILWAY_PROJECT_ID;
  const serviceId = process.env.RAILWAY_SERVICE_ID;
  const environmentId = process.env.RAILWAY_ENVIRONMENT_ID;

  if (!token) {
    console.warn('[youtube-auth] RAILWAY_TOKEN not set — skipping Railway env var update');
    return false;
  }
  if (!projectId || !serviceId || !environmentId) {
    console.warn('[youtube-auth] Railway project/service/environment IDs not available — skipping env var update');
    return false;
  }

  const mutation = `
    mutation UpsertVariables($input: VariableCollectionUpsertInput!) {
      variableCollectionUpsert(input: $input)
    }
  `;

  const res = await fetch('https://backboard.railway.app/graphql/v2', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`,
    },
    body: JSON.stringify({
      query: mutation,
      variables: {
        input: {
          projectId,
          serviceId,
          environmentId,
          variables: { YOUTUBE_COOKIES: cookiesStr },
        },
      },
    }),
  });

  const data = await res.json();
  if (data.errors) {
    console.error('[youtube-auth] Railway API error:', JSON.stringify(data.errors));
    return false;
  }
  console.log('[youtube-auth] Railway env var YOUTUBE_COOKIES updated successfully');
  return true;
}

/**
 * Log in to YouTube with Playwright, return Netscape cookies string.
 */
async function loginAndExportCookies(email, password) {
  console.log('[youtube-auth] Launching Chromium for YouTube login...');
  const browser = await chromium.launch({
    headless: true,
    args: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-blink-features=AutomationControlled',
      '--disable-dev-shm-usage',
      '--window-size=1280,800',
    ],
  });

  const context = await browser.newContext({
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
    viewport: { width: 1280, height: 800 },
    locale: 'en-US',
  });

  try {
    const page = await context.newPage();

    // Remove automation indicator
    await page.addInitScript(() => {
      Object.defineProperty(navigator, 'webdriver', { get: () => undefined });
    });

    // Step 1: Go to Google sign-in
    console.log('[youtube-auth] Navigating to Google sign-in...');
    await page.goto('https://accounts.google.com/signin/v2/identifier?service=youtube&flowName=GlifWebSignIn&flowEntry=ServiceLogin', {
      waitUntil: 'domcontentloaded',
      timeout: 30000,
    });

    // Step 2: Enter email
    await page.waitForSelector('input[type="email"]', { timeout: 15000 });
    await page.fill('input[type="email"]', email);
    await page.waitForTimeout(500);
    await page.click('#identifierNext');
    await page.waitForTimeout(2000);

    // Step 3: Enter password — wait for the visible password field (not the hidden one)
    await page.waitForSelector('input[type="password"]:not([aria-hidden="true"])', { timeout: 15000, state: 'visible' });
    await page.fill('input[type="password"]:not([aria-hidden="true"])', password);
    await page.waitForTimeout(500);
    await page.click('#passwordNext');

    // Step 4: Wait for navigation after login
    try {
      await page.waitForNavigation({ timeout: 20000, waitUntil: 'domcontentloaded' });
    } catch {
      // May not navigate if already on the right page
    }

    const postLoginUrl = page.url();
    console.log(`[youtube-auth] Post-login URL: ${postLoginUrl}`);

    // Check for 2FA / security challenges
    if (
      postLoginUrl.includes('/challenge/') ||
      postLoginUrl.includes('/signin/v2/challenge') ||
      postLoginUrl.includes('2sv') ||
      postLoginUrl.includes('totp')
    ) {
      throw new Error(
        'Google requires 2FA or a security challenge — automated login blocked by Google. ' +
        'Use the manual cookie paste option instead: POST /refresh-youtube-cookies with { "cookies": "..." }.'
      );
    }

    // Step 5: Navigate to YouTube to pick up YouTube-specific cookies
    console.log('[youtube-auth] Navigating to YouTube...');
    await page.goto('https://www.youtube.com', { waitUntil: 'domcontentloaded', timeout: 30000 });
    await page.waitForTimeout(3000);

    // Verify we're signed in by checking for avatar
    const signedIn = await page.$('#avatar-btn, [aria-label*="Account"], ytd-topbar-menu-button-renderer');
    if (!signedIn) {
      console.warn('[youtube-auth] Could not verify sign-in state — exporting cookies anyway');
    } else {
      console.log('[youtube-auth] Sign-in verified on YouTube');
    }

    // Export all cookies for youtube.com and google.com
    const cookies = await context.cookies([
      'https://www.youtube.com',
      'https://accounts.google.com',
      'https://google.com',
    ]);
    console.log(`[youtube-auth] Exported ${cookies.length} cookies`);
    return toNetscapeCookies(cookies);
  } finally {
    await browser.close();
  }
}

/**
 * POST /refresh-youtube-cookies
 *
 * Two modes:
 *   1. Automated: No body required. Uses YOUTUBE_EMAIL + YOUTUBE_PASSWORD env vars
 *      to log in via Playwright Chromium and export fresh cookies.
 *   2. Manual: Body { cookies: "..." } (Netscape format) — skips browser login,
 *      just stores the provided cookies. Use this if Google blocks automated login.
 *
 * In both modes:
 *   - Cookies are cached in memory (immediate effect, no redeploy needed)
 *   - Cookies are written to /tmp/youtube-cookies.txt
 *   - YOUTUBE_COOKIES Railway env var is updated (requires RAILWAY_TOKEN env var)
 */
youtubeAuthRouter.post('/refresh-youtube-cookies', async (req, res) => {
  const { cookies: manualCookies } = req.body ?? {};

  try {
    let cookiesStr;

    if (manualCookies) {
      // Manual paste mode — user exports cookies themselves and POSTs them here
      cookiesStr = manualCookies;
      console.log('[youtube-auth] Using manually provided cookies');
    } else {
      // Automated Playwright mode
      const email = process.env.YOUTUBE_EMAIL;
      const password = process.env.YOUTUBE_PASSWORD;

      if (!email || !password) {
        return res.status(400).json({
          error: 'YOUTUBE_EMAIL and YOUTUBE_PASSWORD env vars required for automated login. ' +
            'Alternatively, POST { cookies: "..." } to use manual cookie paste mode.',
        });
      }

      cookiesStr = await loginAndExportCookies(email, password);
    }

    // Cache in memory — takes effect immediately without redeploy
    _cachedCookiesStr = cookiesStr;

    // Also write to disk so it survives across the request lifecycle
    writeFileSync('/tmp/youtube-cookies.txt', cookiesStr, 'utf8');
    console.log('[youtube-auth] Cookies cached in memory and written to /tmp/youtube-cookies.txt');

    // Persist to Railway env var so cookies survive redeployments
    const railwayUpdated = await updateRailwayEnvVar(cookiesStr);

    const lineCount = cookiesStr.split('\n').filter(l => l && !l.startsWith('#')).length;

    res.json({
      ok: true,
      mode: manualCookies ? 'manual' : 'playwright',
      cookieCount: lineCount,
      railwayUpdated,
      message: railwayUpdated
        ? `${lineCount} cookies updated in memory + Railway env var. Will persist through redeployments.`
        : `${lineCount} cookies updated in memory only. Add RAILWAY_TOKEN env var to also persist through redeployments.`,
    });
  } catch (err) {
    console.error('[youtube-auth] /refresh-youtube-cookies failed:', err.message);
    res.status(500).json({ error: err.message });
  }
});

const OAUTH2_COOKIES_PATH = '/tmp/youtube-oauth2.txt';

/**
 * POST /youtube-oauth2-init
 *
 * Starts yt-dlp's OAuth2 device flow for YouTube.
 * Responds with the authorization URL + code that Shannon visits on her phone.
 * The yt-dlp process continues running in the background until authorization completes,
 * then saves the OAuth2 tokens to memory + Railway env var.
 *
 * ONE-TIME SETUP: once authorized, tokens last until Google revokes them.
 * These tokens bypass YouTube's bot detection because they're a real Google account.
 */
youtubeAuthRouter.post('/youtube-oauth2-init', async (req, res) => {
  console.log('[youtube-oauth2] starting OAuth2 device flow...');

  const ytdlp = spawn('yt-dlp', [
    '--username', 'oauth2',
    '--password', '',
    '--cookies', OAUTH2_COOKIES_PATH,
    '--no-download',
    '--verbose',
    'https://www.youtube.com/',
  ]);

  let authUrl = null;
  let code = null;
  let responseSent = false;

  function tryRespond() {
    if (authUrl && code && !responseSent) {
      responseSent = true;
      console.log(`[youtube-oauth2] auth URL: ${authUrl}, code: ${code}`);
      res.json({
        ok: true,
        authUrl,
        code,
        instructions: `1. Open ${authUrl} on your phone or computer\n2. Enter code: ${code}\n3. Sign in with the YouTube/Google account\n4. Click Allow\nTokens will be saved automatically when authorization completes.`,
      });
    }
  }

  // yt-dlp writes OAuth2 prompts to stderr
  ytdlp.stderr.on('data', (data) => {
    const text = data.toString();
    console.log('[youtube-oauth2]', text.trim());

    const urlMatch = text.match(/https?:\/\/www\.google\.com\/device/);
    const codeMatch = text.match(/[Cc]ode[:\s]+([A-Z0-9]{4}-[A-Z0-9]{4})/);

    if (urlMatch && !authUrl) authUrl = 'https://www.google.com/device';
    if (codeMatch && !code) code = codeMatch[1];

    tryRespond();
  });

  ytdlp.stdout.on('data', (data) => {
    const text = data.toString();
    console.log('[youtube-oauth2-out]', text.trim());

    const urlMatch = text.match(/https?:\/\/www\.google\.com\/device/);
    const codeMatch = text.match(/[Cc]ode[:\s]+([A-Z0-9]{4}-[A-Z0-9]{4})/);

    if (urlMatch && !authUrl) authUrl = 'https://www.google.com/device';
    if (codeMatch && !code) code = codeMatch[1];

    tryRespond();
  });

  ytdlp.on('exit', async (exitCode) => {
    console.log(`[youtube-oauth2] yt-dlp exited with code ${exitCode}`);

    // Check if OAuth2 cookies were written (auth success)
    if (existsSync(OAUTH2_COOKIES_PATH)) {
      try {
        const cookiesStr = readFileSync(OAUTH2_COOKIES_PATH, 'utf8');
        if (cookiesStr.includes('oauth2_access_token') || cookiesStr.trim().length > 100) {
          _cachedCookiesStr = cookiesStr;
          console.log('[youtube-oauth2] OAuth2 tokens saved to memory cache');

          const railwayUpdated = await updateRailwayEnvVar(cookiesStr).catch(() => false);
          console.log('[youtube-oauth2] Railway env var updated:', railwayUpdated);
        }
      } catch (err) {
        console.error('[youtube-oauth2] Failed to read OAuth2 cookies:', err.message);
      }
    }

    if (!responseSent) {
      responseSent = true;
      res.status(500).json({ error: 'OAuth2 flow did not produce an authorization URL. Check Railway logs.' });
    }
  });

  // Timeout safety — respond with error if no URL found in 30s
  setTimeout(() => {
    if (!responseSent) {
      responseSent = true;
      ytdlp.kill();
      res.status(504).json({ error: 'Timeout: yt-dlp did not output an authorization URL within 30 seconds.' });
    }
  }, 30000);
});
