import { Router } from 'express';
import { exec } from 'child_process';
import { promisify } from 'util';
import { unlinkSync, existsSync, readFileSync, createReadStream, statSync, writeFileSync } from 'fs';
import { join } from 'path';
import { randomUUID } from 'crypto';
import { chromium } from 'playwright';
import { Innertube } from 'youtubei.js';
import { getCachedCookies } from './youtube-auth.js';

const execAsync = promisify(exec);

export const youtubeRouter = Router();

const COOKIES_PATH = '/tmp/youtube-cookies.txt';
const ANON_COOKIES_PATH = '/tmp/youtube-anon-cookies.txt';

// In-memory cache for Playwright-generated anonymous cookies.
// These are refreshed automatically when expired or missing.
let _anonCookiesStr = null;
let _anonCookiesFetchedAt = 0;
const ANON_COOKIES_TTL_MS = 30 * 60 * 1000; // 30 minutes

/**
 * Use Playwright (Chromium) to get fresh anonymous YouTube session cookies.
 * These cookies bypass YouTube's bot detection because they come from a real browser.
 * No login required — just browse to YouTube to pick up VISITOR_INFO1_LIVE, YSC, etc.
 */
async function fetchAnonYoutubeCookies() {
  console.log('[youtube] fetching fresh anonymous YouTube cookies via Playwright...');
  const browser = await chromium.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
  });
  try {
    const context = await browser.newContext({
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
      locale: 'en-US',
    });
    const page = await context.newPage();
    // Just load the YouTube homepage to get session cookies — no login
    await page.goto('https://www.youtube.com', { waitUntil: 'domcontentloaded', timeout: 30000 });
    await page.waitForTimeout(2000);
    const cookies = await context.cookies(['https://www.youtube.com', 'https://google.com']);
    // Format as Netscape cookies.txt
    const lines = ['# Netscape HTTP Cookie File', '# Generated by Playwright anonymous session'];
    for (const c of cookies) {
      const domain = c.domain.startsWith('.') ? c.domain : `.${c.domain}`;
      const expires = c.expires > 0 ? Math.floor(c.expires) : Math.floor(Date.now() / 1000 + 3600);
      lines.push(`${domain}\tTRUE\t${c.path || '/'}\t${c.secure ? 'TRUE' : 'FALSE'}\t${expires}\t${c.name}\t${c.value}`);
    }
    const cookiesStr = lines.join('\n');
    console.log(`[youtube] got ${cookies.length} anonymous cookies via Playwright`);
    return cookiesStr;
  } finally {
    await browser.close();
  }
}

const OAUTH2_COOKIES_PATH = '/tmp/youtube-oauth2.txt';

/**
 * Convert a Netscape cookies.txt string to the cookie header string format
 * expected by youtubei.js (Innertube.create({ cookie: "..." })).
 * Netscape line format: domain\tTRUE\tpath\tSECURE\texpires\tname\tvalue
 * Output: name=value; name2=value2; ...
 */
function netscapeCookiesToHeader(netscapeStr) {
  if (!netscapeStr) return null;
  const parts = netscapeStr
    .split('\n')
    .filter(line => line && !line.startsWith('#'))
    .map(line => {
      const cols = line.split('\t');
      if (cols.length < 7) return null;
      const name = cols[5]?.trim();
      const value = cols[6]?.trim();
      if (!name) return null;
      return `${name}=${value}`;
    })
    .filter(Boolean);
  return parts.length > 0 ? parts.join('; ') : null;
}

/**
 * Get the authenticated Netscape cookie string for use with youtubei.js.
 * Returns null if no authenticated cookies are available.
 */
function getAuthCookieString() {
  // OAuth2 cookies file
  if (existsSync(OAUTH2_COOKIES_PATH)) {
    try { return readFileSync(OAUTH2_COOKIES_PATH, 'utf8'); } catch {}
  }
  // Manually-refreshed cookies (from /refresh-youtube-cookies)
  const cached = getCachedCookies();
  if (cached) return cached;
  // Env var fallback
  const envCookies = process.env.YOUTUBE_COOKIES;
  if (envCookies) return envCookies;
  return null;
}

/**
 * Get the --cookies flag for yt-dlp.
 * Priority order:
 *   1. OAuth2 tokens file from /youtube-oauth2-init (real Google account, highest trust)
 *   2. Manually-refreshed cookies (from /refresh-youtube-cookies)
 *   3. Playwright-generated anonymous cookies (auto-refreshed every 30 min)
 *   4. YOUTUBE_COOKIES env var fallback
 */
async function getYtDlpCookiesArg() {
  // Priority 1: OAuth2 tokens from yt-dlp device flow (most trusted)
  if (existsSync(OAUTH2_COOKIES_PATH)) {
    return `--cookies "${OAUTH2_COOKIES_PATH}"`;
  }

  // Priority 2: Manually-provided cookies (logged-in session)
  const cached = getCachedCookies();
  if (cached) {
    writeFileSync(COOKIES_PATH, cached, 'utf8');
    return `--cookies "${COOKIES_PATH}"`;
  }

  // Priority 2: Playwright-generated anonymous cookies (auto-refreshed)
  const now = Date.now();
  if (!_anonCookiesStr || now - _anonCookiesFetchedAt > ANON_COOKIES_TTL_MS) {
    try {
      _anonCookiesStr = await fetchAnonYoutubeCookies();
      _anonCookiesFetchedAt = now;
    } catch (err) {
      console.error('[youtube] Playwright cookie fetch failed:', err.message);
    }
  }
  if (_anonCookiesStr) {
    writeFileSync(ANON_COOKIES_PATH, _anonCookiesStr, 'utf8');
    return `--cookies "${ANON_COOKIES_PATH}"`;
  }

  // Priority 3: Env var fallback (may be expired)
  const cookiesEnv = process.env.YOUTUBE_COOKIES;
  if (cookiesEnv) {
    writeFileSync(COOKIES_PATH, cookiesEnv, 'utf8');
    return `--cookies "${COOKIES_PATH}"`;
  }

  return '';
}

function getSupabaseHeaders() {
  const key = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!key) throw new Error('SUPABASE_SERVICE_KEY not set');
  return {
    apikey: key,
    Authorization: `Bearer ${key}`,
    'Content-Type': 'application/json',
    'Accept-Profile': 'marketing',
    'Content-Profile': 'marketing',
  };
}

function getSupabaseUrl() {
  const url = process.env.SUPABASE_URL;
  if (!url) throw new Error('SUPABASE_URL not set');
  return url;
}

/**
 * Upload a local file to Supabase Storage.
 * Returns the public URL.
 */
async function uploadToSupabaseStorage(filePath, storagePath) {
  const key = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!key) throw new Error('SUPABASE_SERVICE_KEY not set');

  const fileBuffer = readFileSync(filePath);
  const fileSize = statSync(filePath).size;

  const res = await fetch(
    `${getSupabaseUrl()}/storage/v1/object/video-modules/${storagePath}`,
    {
      method: 'POST',
      headers: {
        apikey: key,
        Authorization: `Bearer ${key}`,
        'Content-Type': 'video/mp4',
        'Content-Length': String(fileSize),
        'x-upsert': 'true',
      },
      body: fileBuffer,
    }
  );

  if (!res.ok) throw new Error(`Supabase Storage upload failed: ${await res.text()}`);

  return `${getSupabaseUrl()}/storage/v1/object/public/video-modules/${storagePath}`;
}

async function supabasePatch(table, id, data) {
  const res = await fetch(`${getSupabaseUrl()}/rest/v1/${table}?id=eq.${id}`, {
    method: 'PATCH',
    headers: getSupabaseHeaders(),
    body: JSON.stringify(data),
  });
  if (!res.ok) throw new Error(`Supabase PATCH ${table} failed: ${await res.text()}`);
}

async function supabaseInsert(table, data) {
  const res = await fetch(`${getSupabaseUrl()}/rest/v1/${table}`, {
    method: 'POST',
    headers: { ...getSupabaseHeaders(), Prefer: 'return=representation' },
    body: JSON.stringify(data),
  });
  if (!res.ok) throw new Error(`Supabase POST ${table} failed: ${await res.text()}`);
  return res.json();
}

/**
 * Convert MM:SS or HH:MM:SS timestamp string to total seconds.
 */
function tsToSeconds(ts) {
  const parts = ts.split(':').map(Number);
  if (parts.length === 2) return parts[0] * 60 + parts[1];
  if (parts.length === 3) return parts[0] * 3600 + parts[1] * 60 + parts[2];
  return 0;
}

/**
 * Download a time-ranged clip from a YouTube video using yt-dlp.
 * Returns path to the downloaded mp4 file.
 */
/**
 * Extract the YouTube video ID from any YouTube URL format.
 */
function extractVideoId(url) {
  return url.match(/(?:v=|youtu\.be\/)([a-zA-Z0-9_-]{11})/)?.[1] ?? null;
}

/**
 * Download a time-ranged clip from YouTube using youtubei.js (Innertube API).
 * Uses YouTube's internal mobile app API — bypasses bot detection without cookies.
 * Falls back to yt-dlp if Innertube fails.
 */
async function downloadClip(youtubeUrl, startTs, endTs, outputPath) {
  const startSec = tsToSeconds(startTs);
  const endSec = tsToSeconds(endTs);
  const duration = endSec - startSec;

  if (duration <= 0) throw new Error(`Invalid time range: ${startTs} → ${endTs}`);

  console.log(`[youtube] downloading clip ${startTs}→${endTs} (${duration}s)`);

  // ── Attempt 1: Innertube (youtubei.js) ─────────────────────────────────
  // Uses YouTube's internal mobile client API — works from any IP without cookies.
  try {
    const videoId = extractVideoId(youtubeUrl);
    if (!videoId) throw new Error('Could not extract video ID from URL');

    console.log(`[youtube] Innertube: creating session for ${videoId}...`);
    const authCookieStr = getAuthCookieString();
    const cookieHeader = authCookieStr ? netscapeCookiesToHeader(authCookieStr) : null;
    if (cookieHeader) {
      console.log('[youtube] Innertube: using authenticated cookie session');
    } else {
      console.log('[youtube] Innertube: no authenticated cookies — unauthenticated session (may hit LOGIN_REQUIRED)');
    }
    // Authenticated session (with cookies) — used for ANDROID/IOS which support cookie auth
    const yt = await Innertube.create({
      cache: null,
      generate_session_locally: true,
      ...(cookieHeader && { cookie: cookieHeader }),
    });

    // Anonymous session — used for WEB client to avoid SABR (which is account-level).
    // Shannon's Google account is SABR-enrolled: authenticated WEB returns status=OK but 0 URLs.
    // An anonymous WEB session bypasses SABR and returns direct stream URLs.
    const ytAnon = await Innertube.create({ cache: null, generate_session_locally: true });

    // Try clients in priority order.
    // WEB (anon): avoids SABR enrollment, usually has direct stream URLs.
    // TV_EMBEDDED: not subject to SABR, but geo-restricted from Railway IPs.
    // ANDROID/IOS (auth): cookie auth works, but 400s if cookies are SABR-enrolled.
    // NOTE: youtubei.js v15+ requires { client: 'TYPE' } object, not a plain string.
    const clientsToTry = [
      { client: 'WEB', session: ytAnon },
      { client: 'TV_EMBEDDED', session: yt },
      { client: 'ANDROID', session: yt },
      { client: 'IOS', session: yt },
    ];
    let info = null;
    let adaptiveFormats = [];

    for (const { client, session } of clientsToTry) {
      try {
        const clientInfo = await session.getBasicInfo(videoId, { client });
        const status = clientInfo.playability_status?.status;
        // Only count formats that have an actual URL (SABR formats have no URL)
        const fmts = (clientInfo.streaming_data?.adaptive_formats ?? []).filter(f => f.url);
        console.log(`[youtube] Innertube ${client}: status=${status}, usable formats=${fmts.length}`);
        if (fmts.length > 0) {
          info = clientInfo;
          adaptiveFormats = fmts;
          break;
        }
      } catch (clientErr) {
        console.error(`[youtube] Innertube ${client} error: ${clientErr.message}`);
      }
    }

    if (adaptiveFormats.length === 0) throw new Error('No usable adaptive formats from any Innertube client (WEB-anon, TV_EMBEDDED, ANDROID, IOS)');

    // Pick best MP4 video ≤1080p
    const videoFmt = adaptiveFormats
      .filter(f => f.mime_type?.startsWith('video/mp4') && (f.height ?? 0) <= 1080)
      .sort((a, b) => (b.height ?? 0) - (a.height ?? 0))[0];

    // Pick best MP4 audio
    const audioFmt = adaptiveFormats
      .filter(f => f.mime_type?.startsWith('audio/mp4'))
      .sort((a, b) => (b.bitrate ?? 0) - (a.bitrate ?? 0))[0];

    if (!videoFmt) throw new Error('No MP4 video format found');
    if (!audioFmt) throw new Error('No MP4 audio format found');

    // All clients tried here return pre-deciphered URLs (f.url is set — filtered above)
    const videoUrl = videoFmt.url;
    const audioUrl = audioFmt.url;

    if (!videoUrl) throw new Error('Failed to get video stream URL');
    if (!audioUrl) throw new Error('Failed to get audio stream URL');

    console.log(`[youtube] Innertube: stream URLs ready — extracting ${startTs}→${endTs} via ffmpeg`);

    const tmpVideo = outputPath.replace('.mp4', '_v.mp4');
    const tmpAudio = outputPath.replace('.mp4', '_a.m4a');

    try {
      await execAsync(
        `ffmpeg -ss ${startSec} -t ${duration} -i "${videoUrl}" -c:v copy -y "${tmpVideo}"`,
        { timeout: 300000 }
      );
      await execAsync(
        `ffmpeg -ss ${startSec} -t ${duration} -i "${audioUrl}" -c:a aac -y "${tmpAudio}"`,
        { timeout: 120000 }
      );
      await execAsync(
        `ffmpeg -i "${tmpVideo}" -i "${tmpAudio}" -c:v copy -c:a copy -y "${outputPath}"`,
        { timeout: 60000 }
      );
      console.log(`[youtube] Innertube download complete: ${outputPath}`);
      return;
    } finally {
      if (existsSync(tmpVideo)) unlinkSync(tmpVideo);
      if (existsSync(tmpAudio)) unlinkSync(tmpAudio);
    }
  } catch (innertubeErr) {
    console.error(`[youtube] Innertube failed: ${innertubeErr.message}`);
    // Continue to yt-dlp fallback
  }

  // ── Attempt 2: yt-dlp fallback ───────────────────────────────────────────────
  // SABR issue: Shannon's cookies enroll yt-dlp in SABR experiment (issue #12482)
  // which makes web/ios/web_creator clients return no downloadable URLs.
  // Strategy: try android + tv_embedded clients (SABR-resistant), with and without cookies.
  const cookiesArg = await getYtDlpCookiesArg();
  const baseArgs = [
    `--download-sections "*${startTs}-${endTs}"`,
    '-f "bestvideo[ext=mp4][height<=1080]+bestaudio[ext=m4a]/best[ext=mp4]/best"',
    '--merge-output-format mp4',
    '--no-playlist',
    `--output "${outputPath}"`,
    `"${youtubeUrl}"`,
  ].join(' ');

  const attempts = [
    // web (no cookies, anonymous) + node JS runtime: avoids SABR (account-level), node solves n-challenge
    `yt-dlp --js-runtimes node --extractor-args "youtube:player_client=web" ${baseArgs}`,
    // web + cookies + node: node handles SABR protocol natively in newer yt-dlp versions
    `yt-dlp --js-runtimes node ${cookiesArg} --extractor-args "youtube:player_client=web" ${baseArgs}`,
    // android/ios without cookies: no n-challenge needed (mobile API), last resort
    `yt-dlp --extractor-args "youtube:player_client=android" ${baseArgs}`,
    `yt-dlp --extractor-args "youtube:player_client=ios" ${baseArgs}`,
  ];

  for (const cmd of attempts) {
    try {
      console.log(`[youtube] yt-dlp attempt: ${cmd.slice(0, 80)}...`);
      await execAsync(cmd, { timeout: 300000 });
      if (existsSync(outputPath)) return;
    } catch (e) {
      console.error(`[youtube] yt-dlp attempt failed: ${e.message.split('\n').slice(0, 3).join(' | ')}`);
    }
  }
  throw new Error('All yt-dlp attempts failed — see logs above for details');
}

/**
 * Detect the speaker's face in a video frame.
 * Returns { cx, speakerSide } — speakerSide is 'left' or 'right'.
 */
async function detectFace(videoPath) {
  const framePath = videoPath.replace('.mp4', '_frame.jpg');
  try {
    await execAsync(`ffmpeg -ss 1 -i "${videoPath}" -frames:v 1 -y "${framePath}"`, { timeout: 15000 });
    const scriptPath = new URL('../lib/detect_face.py', import.meta.url).pathname;
    const { stdout } = await execAsync(`python3 "${scriptPath}" "${framePath}"`, { timeout: 15000 });
    const result = JSON.parse(stdout.trim());
    if (result.cx != null) {
      console.log(`[youtube] face detected at x=${result.cx}, side=${result.speaker_side}`);
      return { cx: result.cx, speakerSide: result.speaker_side };
    }
    console.log('[youtube] no face detected, defaulting to left=speaker');
    return { cx: null, speakerSide: 'left' };
  } catch (err) {
    console.warn('[youtube] face detection failed:', err.message);
    return { cx: null, speakerSide: 'left' };
  } finally {
    if (existsSync(framePath)) unlinkSync(framePath);
  }
}

/**
 * Convert a landscape YouTube clip to portrait (1080x1920).
 * Uses face detection to center the crop on the speaker.
 * Overwrites the file in place.
 */
async function convertToPortraitSplit(inputPath) {
  const outputPath = inputPath.replace('.mp4', '_portrait.mp4');
  try {
    // Detect input dimensions
    const { stdout } = await execAsync(
      `ffprobe -v quiet -select_streams v:0 -show_entries stream=width,height -of csv=p=0 "${inputPath}"`
    );
    const [w, h] = stdout.trim().split(',').map(Number);
    console.log(`[youtube] input dimensions: ${w}x${h}`);

    // If already portrait or near-square, just scale to 1080x1920
    if (h >= w) {
      await execAsync(
        `ffmpeg -i "${inputPath}" ` +
        `-vf "scale=1080:1920:force_original_aspect_ratio=increase,crop=1080:1920" ` +
        `-c:v libx264 -preset fast -crf 23 -c:a aac -movflags +faststart -y "${outputPath}"`,
        { timeout: 120000 }
      );
    } else {
      // Detect which side the speaker is on
      const { speakerSide } = await detectFace(inputPath);

      // Split left/right halves — speaker goes TOP, content/guest goes BOTTOM.
      // Layout: [top = speaker face] [bottom = guest/content]
      // Reason: Submagic places animated captions in the center of the lower half.
      // Putting the featured speaker on top keeps their face caption-free.
      const speakerCrop = speakerSide === 'left'
        ? `crop=iw/2:ih:0:0` // left half = speaker
        : `crop=iw/2:ih:iw/2:0`; // right half = speaker
      const contentCrop = speakerSide === 'left'
        ? `crop=iw/2:ih:iw/2:0` // right half = content
        : `crop=iw/2:ih:0:0`; // left half = content

      console.log(`[youtube] speaker on ${speakerSide} → speaker=top, content=bottom`);
      // scale to fit (not fill) so full body stays visible — pad black bars on sides if needed
      const fitScale = `scale=1080:960:force_original_aspect_ratio=decrease,pad=1080:960:(ow-iw)/2:(oh-ih)/2`;
      await execAsync(
        `ffmpeg -i "${inputPath}" ` +
        `-filter_complex "[0:v]${speakerCrop},${fitScale}[top];[0:v]${contentCrop},${fitScale}[bottom];[top][bottom]vstack[out]" ` +
        `-map "[out]" -map 0:a -c:v libx264 -preset fast -crf 23 -c:a aac -movflags +faststart -y "${outputPath}"`,
        { timeout: 120000 }
      );
    }

    unlinkSync(inputPath);
    await execAsync(`mv "${outputPath}" "${inputPath}"`);
    console.log(`[youtube] converted to portrait (${w}x${h} → 1080x1920): ${inputPath}`);
  } catch (err) {
    if (existsSync(outputPath)) unlinkSync(outputPath);
    throw err;
  }
}

/**
 * Download transcript (auto-generated captions) from a YouTube video.
 * Returns the raw VTT text, or null if unavailable.
 */
async function downloadTranscript(youtubeUrl, tmpDir) {
  const cookiesArg = await getYtDlpCookiesArg();
  const vttPath = join(tmpDir, 'transcript.en.vtt');

  // Try iOS client with Playwright cookies
  try {
    await execAsync(
      `yt-dlp ${cookiesArg} --extractor-args "youtube:player_client=ios" --write-auto-subs --sub-langs en --sub-format vtt --skip-download --no-playlist -o "${tmpDir}/transcript" "${youtubeUrl}"`,
      { timeout: 60000 }
    );
    if (existsSync(vttPath)) return readFileSync(vttPath, 'utf8');
  } catch {
    // fall through
  }

  // Fall back to web_creator
  try {
    await execAsync(
      `yt-dlp ${cookiesArg} --extractor-args "youtube:player_client=web_creator" --write-auto-subs --sub-langs en --sub-format vtt --skip-download --no-playlist -o "${tmpDir}/transcript" "${youtubeUrl}"`,
      { timeout: 60000 }
    );
    if (existsSync(vttPath)) return readFileSync(vttPath, 'utf8');
    return null;
  } catch {
    return null;
  }
}

/**
 * POST /youtube-extract-async
 *
 * Fire-and-forget: accepts immediately, processes in background.
 * Downloads clip segments from a YouTube video, uploads to Cloudinary,
 * creates ad_ingestion rows so the render pipeline picks them up.
 *
 * Body: {
 *   clipPlanId: string
 *   youtubeUrl: string
 *   videoTitle: string
 *   clientId: string
 *   clips: Array<{ title, startTimestamp, endTimestamp, suggestedCaption }>
 * }
 */
youtubeRouter.post('/youtube-extract-async', async (req, res) => {
  const { clipPlanId, youtubeUrl, videoTitle, clientId, clips } = req.body;
  if (!clipPlanId || !youtubeUrl || !clientId || !Array.isArray(clips)) {
    return res.status(400).json({ error: 'clipPlanId, youtubeUrl, clientId, clips required' });
  }

  res.json({ accepted: true, clipPlanId, clipCount: clips.length });

  setImmediate(async () => {
    const tmpDir = `/tmp/yt-${randomUUID()}`;
    await execAsync(`mkdir -p "${tmpDir}"`);

    try {
      console.log(`[youtube] starting extraction for plan ${clipPlanId} (${clips.length} clips)`);

      const extractedClips = [];

      for (let i = 0; i < clips.length; i++) {
        const clip = clips[i];
        const clipPath = join(tmpDir, `clip_${i}.mp4`);

        try {
          await downloadClip(youtubeUrl, clip.startTimestamp, clip.endTimestamp, clipPath);

          if (!existsSync(clipPath)) {
            console.warn(`[youtube] clip ${i} file not found after download, skipping`);
            continue;
          }

          // Convert landscape to portrait split-screen (host bottom, guest top)
          await convertToPortraitSplit(clipPath);

          // Upload to Supabase Storage
          const date = new Date().toISOString().split('T')[0];
          const safeFilename = (clip.title ?? `clip_${i}`).replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 60);
          const storagePath = `youtube-clips/${clientId}/${date}/${randomUUID()}_${safeFilename}.mp4`;
          const clipUrl = await uploadToSupabaseStorage(clipPath, storagePath);
          console.log(`[youtube] clip ${i} uploaded: ${clipUrl}`);

          // Create ad_ingestion row — pipeline will add captions via Submagic
          const safeTitle = clip.title?.slice(0, 100) ?? `Clip ${i + 1}`;
          const filename = `${safeTitle}.mp4`;

          await supabaseInsert('ad_ingestion', {
            client_id: clientId,
            uploaded_by: clientId,
            upload_source: 'youtube_clip',
            asset_type: 'reel_raw',
            format: 'video',
            file_url: clipUrl,
            original_filename: filename,
            status: 'classified',
            gemini_markup: {
              source: 'youtube',
              youtube_url: youtubeUrl,
              video_title: videoTitle,
              clip_title: clip.title,
              suggested_caption: clip.suggestedCaption ?? null,
              broll_cues: [],
              emotion_tags: [],
            },
          });

          extractedClips.push({ title: clip.title, url: clipUrl });
        } catch (clipErr) {
          console.error(`[youtube] clip ${i} failed:`, clipErr.message);
          // Persist error to pipeline events so we can diagnose without Railway logs
          await supabaseInsert('content_pipeline_events', {
            client_id: clientId,
            event_type: 'error',
            source_module: 'youtube/clip-extraction',
            metadata: {
              clip_plan_id: clipPlanId,
              clip_index: i,
              clip_title: clip.title,
              error: clipErr.message,
              start: clip.startTimestamp,
              end: clip.endTimestamp,
            },
          }).catch(() => {});
        }

        // Cleanup clip temp file
        if (existsSync(clipPath)) unlinkSync(clipPath);
      }

      // Mark plan as extracted
      await supabasePatch('youtube_clip_plans', clipPlanId, {
        extraction_status: extractedClips.length > 0 ? 'extracted' : 'dispatch_failed',
      });

      console.log(`[youtube] done: ${extractedClips.length}/${clips.length} clips extracted for plan ${clipPlanId}`);
    } catch (err) {
      console.error(`[youtube] extraction failed for plan ${clipPlanId}:`, err.message);
      await supabaseInsert('content_pipeline_events', {
        client_id: clientId,
        event_type: 'error',
        source_module: 'youtube/extraction-outer',
        metadata: { clip_plan_id: clipPlanId, error: err.message },
      }).catch(() => {});
      await supabasePatch('youtube_clip_plans', clipPlanId, {
        extraction_status: 'dispatch_failed',
      }).catch(() => {});
    } finally {
      // Cleanup temp dir
      execAsync(`rm -rf "${tmpDir}"`).catch(() => {});
    }
  });
});

/**
 * POST /youtube-transcript
 *
 * Returns the VTT transcript for a YouTube video.
 * Used by Vercel to get transcript before calling Gemini for clip identification.
 */
youtubeRouter.post('/youtube-transcript', async (req, res, next) => {
  const { youtubeUrl } = req.body;
  if (!youtubeUrl) return res.status(400).json({ error: 'youtubeUrl required' });

  const tmpDir = `/tmp/transcript-${randomUUID()}`;
  try {
    await execAsync(`mkdir -p "${tmpDir}"`);
    const transcript = await downloadTranscript(youtubeUrl, tmpDir);
    res.json({ transcript, available: transcript !== null });
  } catch (err) {
    next(err);
  } finally {
    execAsync(`rm -rf "${tmpDir}"`).catch(() => {});
  }
});
